version: "3.9"
services:
    web:
      build: .
      volumes:
        - .:/app
      ports:
        - 8000:8000
      command: sh -c "python manage.py wait_for_db &&
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000" 
      environment:
        - DB_HOST=db
        - DB_NAME=recipe
        - DB_USER=postgres
        - DB_PASSWORD=supersecretpassword
      depends_on:
        - db
    
    db:
      image: postgres:16-alpine
      environment:
        - POSTGRES_DB=recipe
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=supersecretpassword